#!/usr/bin/perl

use strict;
use warnings;

use Getopt::Long;
use Log::Log4perl;
use BassyBot;

my $username = 'bassytime';

my $encoding = '';
my $password = '';
my $nossl = 0;

GetOptions(
	'encoding=s' => \$encoding,
	'pass=s' => \$password,
	'nossl' => \$nossl,
);

die "--pass='YourPassword' plz.\n" unless $password;

Log::Log4perl->init("bassy-bot-logger.conf");

binmode STDOUT, ":encoding($encoding)" if $encoding;
binmode STDERR, ":encoding($encoding)" if $encoding;

BassyBot->new(username => $username, password => $password, ssl => ! $nossl)->start;



