#!/usr/bin/perl

use strict;
use warnings;

use Getopt::Long;
use BassyBot;

my $username = 'bassytime';

my $sjis = 0;
my $password = '';
my $nossl = 0;

GetOptions(
	'sjis' => \$sjis,
	'pass=s' => \$password,
	'nossl' => \$nossl,
);

die "--pass='YourPassword' plz.\n" unless $password;

binmode STDOUT, ':encoding(shiftjis)' if $sjis; 

BassyBot->new(username => $username, password => $password, ssl => ! $nossl)->start;



